//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solid_spork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int QueryId { get; set; }
        public string QueryDescription { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public bool IsActive { get; set; }
        public int QueryViews { get; set; }
        public string QueryData { get; set; }
    }
}
